#!/bin/bash

# DNS Configuration Display Script
# سكريبت عرض إعدادات DNS المطلوبة

echo "🔧 إعدادات DNS المطلوبة لـ wasl.store"
echo "🔧 Required DNS Configuration for wasl.store"
echo "=================================================="
echo ""
echo "📋 السجلات المطلوبة | Required Records:"
echo ""
echo "🌐 سجلات A للنطاق الرئيسي | A Records for Root Domain:"
echo "─────────────────────────────────────────────────"
echo "Type: A"
echo "Name: @ (or leave empty/wasl.store)"
echo "Value: 185.199.108.153"
echo "TTL: 300"
echo ""
echo "Type: A" 
echo "Name: @ (or leave empty/wasl.store)"
echo "Value: 185.199.109.153"
echo "TTL: 300"
echo ""
echo "Type: A"
echo "Name: @ (or leave empty/wasl.store)" 
echo "Value: 185.199.110.153"
echo "TTL: 300"
echo ""
echo "Type: A"
echo "Name: @ (or leave empty/wasl.store)"
echo "Value: 185.199.111.153" 
echo "TTL: 300"
echo ""
echo "🌐 سجل CNAME للـ www | CNAME Record for www:"
echo "─────────────────────────────────────────────────"
echo "Type: CNAME"
echo "Name: www"
echo "Value: wasalstor-web.github.io."
echo "TTL: 300"
echo ""
echo "=================================================="
echo "📝 ملاحظات | Notes:"
echo "• تأكد من إضافة نقطة (.) في نهاية wasalstor-web.github.io."
echo "• Make sure to add a dot (.) at the end of wasalstor-web.github.io."
echo "• قد تستغرق التغييرات من 5 دقائق إلى 48 ساعة للانتشار"
echo "• Changes may take 5 minutes to 48 hours to propagate"
echo "• استخدم ./verify-domain.sh للتحقق من الإعدادات"
echo "• Use ./verify-domain.sh to verify the configuration"